version: "3.7"
services:
  mbarttrainer:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: mBart50
    working_dir: /app/src
    volumes:
      - ./src:/app/src
      - ./saved_model:/app/saved_model
    command: python3 trainer.py
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  streamlit:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: streamlit
    working_dir: /app/src
    command: streamlit run streamlit_demo.py --server.port 8502
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
